version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prom
    volumes:
      - ./config/:/etc/prometheus/
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    container_name: grafana
    depends_on:
      - prometheus
    ports: 
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor 
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/bocker/:/var/lib/docker:ro
    ports:
      - 9000:8080
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100